[WebDriver]
chrome_driver_path = ".\"
gecko_driver_path = ".\"
edge_driver_path = ""
ie_driver_path = ""
opera_driver_path = ""
safari_driver_path = ""

[Browser]
browser_type = "chrome"
is_headless = true
    [Resolution]
    length = 1920
    width = 1200

[Application]
linkedin_url = "https://in.linkedin.com/"